### ISSUE TITLE
偶尔会自己报错，大佬给看看

### ISSUE THREAD

**Issue by ghost** [good-good-study/scroll_page_view#1]
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 108 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:108:12)
#3      PageController.jumpToPage (package:flutter/src/widgets/page_view.dart:208:41)
#4      _State._onPageChanged (package:scroll_page_view/pager/scroll_page_view.dart:305:31)

**Comment by good-good-study** [comment]
ScrollController not attached to any scroll views.


你是没有给它提供Controller吧






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "good-good-study/scroll_page_view"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月9日(星期六) 晚上8:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[good-good-study/scroll_page_view] 偶尔会自己报错，大佬给看看 (#1)





 
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 108 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
 #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
 #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
 #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:108:12)
 #3      PageController.jumpToPage (package:flutter/src/widgets/page_view.dart:208:41)
 #4      _State._onPageChanged (package:scroll_page_view/pager/scroll_page_view.dart:305:31)
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ghost** [comment]
> ScrollController not attached to any scroll views. 你是没有给它提供Controller吧
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "good-good-study/scroll_page_view" ***@***.***&gt;; 发送时间:&nbsp;2021年10月9日(星期六) 晚上8:50 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[good-good-study/scroll_page_view] 偶尔会自己报错，大佬给看看 (#1) [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 108 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views. #0 _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39) #1 _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5) #2 ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:108:12) #3 PageController.jumpToPage (package:flutter/src/widgets/page_view.dart:208:41) #4 _State._onPageChanged (package:scroll_page_view/pager/scroll_page_view.dart:305:31) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

这是我的代码

```
ScrollPageView(
              key: Key(DateTime.now().microsecond.toString()),
              indicatorPadding: EdgeInsets.only(bottom: 12.h, right: 11.w),
              controller: ScrollPageController(),
              delay: const Duration(seconds: 5),
              indicatorWidgetBuilder: (
                BuildContext context,
                int index,
                int length,
              ) {
                return CustomIndicator(index: index, length: length);
              },
              indicatorAlign: Alignment.bottomRight,
              children: bannerList.map((banner) => bannerItem(banner)).toList(),
            )
```

**Comment by good-good-study** [comment]
我测试下来没有报错呀，你的这段代码，会不会跟你的使用场景有关系，是在列表里吗？

`ScrollPageView(
                isTimer: false,
                controller: ScrollPageController(),
                indicatorAlign: Alignment.bottomRight,
                indicatorWidgetBuilder: (_, index, length) {
                  return _indicatorBuilder(index, length);
                },
                children: widget.goods.imageInfo.imageList
                    .map((image) => _imageView(context, image))
                    .toList(),
              )`

**Comment by good-good-study** [comment]
我测试下来没有报错呀，你的这段代码，会不会跟你的使用场景有关系，是在列表里吗？

`ScrollPageView(
                isTimer: false,
                controller: ScrollPageController(),
                indicatorAlign: Alignment.bottomRight,
                indicatorWidgetBuilder: (_, index, length) {
                  return _indicatorBuilder(index, length);
                },
                children: widget.goods.imageInfo.imageList
                    .map((image) => _imageView(context, image))
                    .toList(),
              )`

**Comment by good-good-study** [comment]
我测试下来没有报错呀，你的这段代码，会不会跟你的使用场景有关系，是在列表里吗？

```
  ScrollPageView(
                  isTimer: false,
                  controller: ScrollPageController(),
                  indicatorAlign: Alignment.bottomRight,
                  indicatorWidgetBuilder: (_, index, length) {
                    return _indicatorBuilder(index, length);
                  },
                  children: widget.goods.imageInfo.imageList
                      .map((image) => _imageView(context, image))
                      .toList(),
                )
```
